version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_db_epsi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database_cours
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_epsi
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      - db

  php:
    build: .
    container_name: php_server_epsi
    ports:
      - "9000:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db

volumes:
  db_data:
